# Generated by Django 3.2.10 on 2021-12-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='read_posts',
            field=models.ManyToManyField(to='blogs.Post', verbose_name='прочитанные посты'),
        ),
    ]
